name: Static Checks

on: push

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check Markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.github/workflows/static/mlc_config.json'
        use-verbose-mode: 'yes'
        # don't go down duniverse/
        max-depth: 1
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
